Added install instructions to README
willeccles/cpm pull request #13
Opened 2020-09-07 23:26 UTC by ThatOneCalculator

2020-09-08 13:03 UTC, willeccles commented
I'm hesitant to merge this just because the install instructions are fairly complicated. I see no reason why the install instructions couldn't be something like `sudo install -m755 cpm /usr/bin/cpm` or something. Is there a reason for your complicated instructions? I'm definitely open to suggestions.

2020-09-09 16:13 UTC, ThatOneCalculator commented
I wasn't aware of that install command, I'll look into that!

2020-09-09 16:17 UTC, ThatOneCalculator commented
@willeccles Ok, I tested and implemented that instruction. Please re-review the new README! :smile:

2020-09-09 17:34 UTC, willeccles requested changes

2020-09-09 17:34 UTC, willeccles commented on README.md
> +## Installation:
Also, remove the colon from this line, like with Usage. In fact, I'd appreciate if you removed all the colons on the header lines, not sure why I put them there in the first place.

2020-09-09 17:37 UTC, ThatOneCalculator commented
Done!

2020-09-09 17:37 UTC, merged