attempt to add Portage(emerge) and some fixes for apk
willeccles/cpm pull request #16
Opened 2020-09-23 19:59 UTC by tanmatsu-cmd

Hey again!

This is an attempt to add Portage (emerge),  [Gentoo](https://gentoo.org/)'s package manager. Alongside some minor fixes on apk.

## PORTAGE NOTES

- Listing installed packages is only doable via an external program (`qlist -IRv`) *or* using coreutils 

- Displaying a count of all packages is also only doable via an external program (`eix --world | tot`) *or* using coreutils

2020-09-23 23:02 UTC, willeccles commented on cpm
> +	count)   echo "eix --world | tot";;
What's up with the `echo` here?

2020-09-23 23:04 UTC, willeccles commented
> Listing installed packages is only doable via an external program (qlist -IRv) or using coreutils

I doubt this could only be done with coreutils or an external program. However, if this external program is likely to be installed, it may be worth using. Could you elaborate?

2020-09-24 10:16 UTC, tanmatsu-cmd commented
> What's up with the `echo` here?

It's put as a placeholder. Portage does not have any programs for listing programs by itself.

> I doubt this could only be done with coreutils or an external program. However, if this external program is likely to be installed, it may be worth using. Could you elaborate?

Said programs needed would be `qlist` and `eix`, most Gentoo users are likely to install them but if needed I could make cpm possibly check for them too. As for why this or coreutils would be the only way is explained above.

2020-09-24 13:32 UTC, willeccles commented
Okay, I think what should be done is to make those two cases multiple lines, so that you end up with something like this:

```bash
list)
    if has qlist; then
        # do that here
    elif has otherthing; then
        # do other things here
    else
        >&2 echo "Could not find program1 or program2"
        exit 1
    fi
    ;;
```

2020-09-24 15:35 UTC, tanmatsu-cmd commented
> Okay, I think what should be done is to make those two cases multiple lines, so that you end up with something like this:
> 
> ```shell
> list)
>     if has qlist; then
>         # do that here
>     elif has otherthing; then
>         # do other things here
>     else
>         >&2 echo "Could not find program1 or program2"
>         exit 1
>     fi
>     ;;
> ```

Good idea! Will get started on it.

2020-09-24 15:53 UTC, willeccles requested changes

2020-09-24 15:53 UTC, willeccles commented on cpm
> +			>&2 echo "Could not find program eix"
Add `exit 1` to these `else` statements.

2020-09-24 15:53 UTC, willeccles commented on cpm
> +		 	>&2 echo "Could not find program qlist"
Remove "program," just leave "Could not find qlist"

2020-09-24 16:23 UTC, willeccles commented
In the future, use spaces instead of tabs. However, I will merge this and update it myself, as I am going to add a modeline to all my projects' source files from now on anyway.

2020-09-24 16:23 UTC, merged