Add FreeBSD pkg
willeccles/cpm pull request #66
Opened 2022-10-04 18:55 UTC by swindlesmccoop

2022-10-04 19:51 UTC, willeccles requested changes

2022-10-04 19:51 UTC, willeccles commented on cpm
> +    elif command -v doas >/dev/null && [ -f /etc/doas.conf ] || [ -f /usr/local/etc/doas.conf ]; then
The logic here is broken. While this is unlikely to be an issue, this is equivalent to: `if ((a && b) || c)`, so `doas` does not need to exist for this to attempt to use it. Please add `()` around the `||` clause.

2022-10-05 14:37 UTC, willeccles requested changes
Please update README.md to add this to the list of supported package managers.

2022-10-05 20:52 UTC, swindlesmccoop commented
Ready for merge

2022-10-05 22:22 UTC, willeccles approved these changes

2022-10-05 22:23 UTC, merged